In [1]:
import numpy as np
arr5=np.random.randint(10,50,(6,5))
print(arr5)
print(arr5.size)
print(arr5.mean())

[[44 11 20 13 14]
 [41 20 35 21 39]
 [40 22 25 40 16]
 [28 22 46 28 23]
 [11 47 27 45 22]
 [15 22 39 10 33]]
30
27.3
