In [1]:
import numpy as np
arr4=np.random.randint(10,50,(10,10))
print(arr4)
arr4.min(), arr4.max()

[[20 28 32 30 21 42 32 39 41 14]
 [36 32 31 27 14 42 48 19 47 47]
 [34 35 19 15 18 48 27 25 34 49]
 [14 30 36 34 40 22 15 29 31 40]
 [20 30 10 38 22 25 41 13 41 20]
 [25 43 32 36 23 49 34 43 30 11]
 [46 38 25 31 20 16 36 32 41 30]
 [32 23 33 27 21 35 42 10 36 26]
 [44 34 13 33 34 26 15 27 21 45]
 [21 26 18 43 22 40 31 30 20 33]]


(10, 49)